<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Data' => '业务数据',
    'Description' => '描述',
    'Name' => '名称',
    'Rule Name' => '权限规则名',
    'Type' => '权限类型',
    'User ID' => '用户id',
    'Are you sure you want to delete this item?' => '您确定要删除选中项吗？',
    'Auth Items' => '权限项',
    'Create Auth Item' => '添加权限项',
    'Created At' => '添加时间',
    'Delete' => '删除',
    'Item Name' => '项名称',
    'Permisstion' => '权限',
    'Reset' => '重置',
    'Role' => '角色',
    'Search' => '搜索',
    'Update' => '修改',
    'Update {modelClass}: ' => '修改',
    'Updated At' => '修改时间',
    'Auth Operation' => '授权操作',
    'Delete failure,this role has been used!' => '删除失败，这个角色正在被使用！',
    'Update failure,this role has been used,do not modify the role name!' => '更新失败，这个角色正在被使用，不能修改角色名称！',
    'Auth for {des}' => '授权给{des}',
    'Auth' => '授权',
    'Auth Config' => '授权配置',
    'Reset Auth' => '重置权限',
    'Update Role Success' => '修改角色成功',
    'Task' => '任务',
    'Progress...' => '处理中...',
];