<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '你确定要删除选中的项吗？',
    'Author' => '作者',
    'Boldval' => '字号',
    'Cms Ad List' => '广告列表',
    'Cms Ad Type ID' => '广告位',
    'Cms Ad Type List' => '广告位列表',
    'Cms Ads' => '广告列表',
    'Cms Class ID' => '栏目ID',
    'Cms Classe List' => '栏目列表',
    'Cms Flag List' => '标记列表',
    'Cms Img List' => '图片类型列表',
    'Cms List List' => '内容类型列表',
    'Cms Page List' => '单页面类型列表',
    'Colorval' => '颜色',
    'Content' => '主体内容',
    'Create' => '添加',
    'Create Cms Ad' => '广告',
    'Create Cms Ad Type' => '广告位',
    'Create Cms Class' => '栏目',
    'Create Cms Flag' => '标记',
    'Create Cms Img' => '图片类型',
    'Create Cms List' => '内容类型',
    'Create Cms Page' => '单面类型',
    'Created At' => '添加时间',
    'Delete' => '删除',
    'Description' => '描述',
    'Flag' => '标记',
    'Height' => '高',
    'Hits' => '点击次数',
    'ID' => 'ID',
    'Keywords' => '关键词',
    'Link Url' => '链接',
    'Linkurl' => '',
    'Mode' => '类型',
    'Name' => '名称',
    'Order' => '排序',
    'Parent ID' => '父ID',
    'Parent Str' => '',
    'Pic Height' => '图片高',
    'Pic Url' => '图片地址',
    'Pic Width' => '图片宽',
    'Picarr' => '图片组',
    'Reset' => '重置',
    'Search' => '搜索',
    'Seo Title' => 'SEO标题',
    'Source' => '源地址',
    'Status' => '状态',
    'Text' => '内容',
    'Title' => '标题',
    'Type' => '类型',
    'Update' => '更新',
    'Update:' => '更新：',
    'Updated At' => '更新时间',
    'Width' => '宽',
    'Unknown Type' => '未知',
    'List' => '列表',
    'Image' => '图片',
    'Page' => '单页',
];
