<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'ID' => 'ID',
    'Are you sure you want to delete this item?' => '你确定要删除选中的项吗？',
    'Author' => '作者',
    'Boldval' => '字号',
    'Ad List' => '广告列表',
    'Ad Type List' => '广告位列表',
    'Column' => '所属栏目',
    'Column List' => '栏目列表',
    'Flag List' => '标记列表',
    'Img List' => '图片类型列表',
    'List List' => '内容类型列表',
    'Page List' => '单页面列表',
    'Colorval' => '颜色',
    'Content' => '主体内容',
    'Create' => '添加',
    'Create Ad' => '添加：广告',
    'Create Ad Type' => '添加：广告位',
    'Create Column' => '添加：栏目',
    'Create Flag' => '添加：标记',
    'Create Img' => '添加：图片类型',
    'Create List' => '添加：内容类型',
    'Create Page' => '添加：单面类型',
    'Created At' => '添加时间',
    'Delete' => '删除',
    'Description' => '描述',
    'Flag' => '标记',
	'Flag Name' => '标记名',
    'Height' => '高度',
    'Hits' => '点击次数',
    'Keywords' => '关键词',
    'Link Url' => '链接',
    'Mode' => '类型',
    'Name' => '名称',
    'Order' => '排序',
    'Pic Height' => '图片高',
    'Pic Url' => '图片地址',
    'Pic Width' => '图片宽',
    'Picarr' => '组图',
    'Reset' => '重置',
    'Search' => '搜索',
    'Seo Title' => 'SEO标题',
    'Source' => '来源',
	'Article Source' => '文章来源',
    'Status' => '发布',
    'Text' => '内容',
    'Title' => '标题',
    'Update' => '更新',
    'Update:' => '更新：',
    'Updated At' => '更新时间',
	'Publish At' => '发布时间',
    'Width' => '宽度',
	'Top Column' => '顶级栏目',
	
	'Page' => '单页面',
    'List' => '文章列表',
	'Download' => '资源下载',
	
	'Add Column' => '添加栏目',
	'Add New Column' => '添加新栏目',
	'Belong Column' => '所属栏目',
	'Column List' => '栏目列表',
	'Flag List' => '标识列表',
	'Img List' => '图片列表',
	'List List' => '文章列表',
	'Page List' => '单页面列表',
	'Column Description' => '栏目描述',
	'Column Keywords' => '栏目关键词',
	'Column Name' => '栏目名称',
	'Column Type' => '栏目类型',
	'Linkurl' => '链接地址',
	'Update Status' => '更新状态',
		
	'Yes' => '已发布',
	'No' => '未发布',
		
	'Under this column subtopic, are not allowed to delete directly!' => '此分类下有子分类，不允许直接删除.',
	'Under this category contains content, cannot be deleted!' => '此分类下包含有内容，不能删除.',
		
	'Title is required' => '注意：标题为必填项.',
	'Title Color' => '标题颜色',
	'Title Bold' => '标题加粗',
	'With a blank or ", "between multiple keywords' => '多个关键词之间使用空格或逗号","隔开.',
	'Don\'t show in the frontend,If you don\'t choose' => '如果不选择，在前台将不会显示.',
	'Accredit' => '授权',
	'Clear' => '清除',
	'Ad Type' => '广告位',
	'Column' => '所属栏目',
	'Download List' => '文件资源列表',
	'Create Download' => '添加：文件资源',
	'Deleted' => '已删除',
	'Down Url' => '下载地址',
	'File Size' => '文件大小',
	'File Type' => '文件类型',
	'Language' => '资源语言',
	'Order is success!' => '排序成功！',
	'Picurl' => '图片路径',
	'Request is failure!' => '请求失败！',
	'Run Os' => '支持的操作系统',
	'Unit' => '单元',
		
	'Short Code' => '调用简码',
	'Size Type' => '尺寸类型',
	'Pixel' => '像素',
	'Percent' => '百分比',
	'If is blank, default as 100%' => '如果留空，则默认为100%',
	'Unit is pixel,' => '单位为像素，',
	'Click on the column headings first access this link' => '点击栏目标题优先访问此链接，留空则正常访问',
	'Site address, please fill in the  http:// beginning' => '网址请以http://开头',
	'Image' => '图片',
	'Flash' => 'Flash动画',
    'Video' => '视频',
    'HTML Code' => 'HTML代码',
	'Null' => '未设置',
	'Preview in frontend' => '在前台预览',
];
