<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Home' => '首页',
    'Online' => '在线',
    'Are you sure you want to delete this item?' => '您确定要删除选中项吗？',
    'Click' => '单击进入',
    'Create' => '添加',
    'Delete' => '删除',
    'Index' => '列表',
    'Opration' => '操作',
    'Update' => '修改',
    'View' => '查看',
    'Update {modelClass}: ' => '修改',
    'Updated At' => '修改时间',
    'Created At' => '添加改时间',
    'Create Failure!' => '添加失败',
    'Create Success!' => '添加成功',
    'Update Failure!' => '修改失败',
    'On' => '开启',
    'Off' => '关闭',
    'Male' => '男',
    'Female' => '女',
    'Passed' => '通过',
    'Forbid' => '禁止',
    'Default' => '默认',
    'Not Default' => '非默认',
    'You have not login, please login first.' => '请先登录才可访问。',
    'Guest' => '游客',
    'Adress Admin' => '地址管理',
    'DEMO' => 'DEMO',
    'Please check your upload file or file name!' => '请检查您上传的文件或者文件名！',
    'Failed to create the images directory!' => '创建图片路径不成功！',
    'Blank' => '未找到',
	'No' => 'No',
	'Yes' => 'Yes',
	'turen' => '土人',
	'All' => '全部',
];