<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '地址',
    'Approval' => '批准',
    'Are you sure you want to delete this item?' => '您确定要删除选中的项目吗？',
    'Birthday' => '生日',
    'City' => '城市',
    'Consignee' => '收货人',
    'Country' => '国家',
    'Create' => '添加',
    'Create Customer' => '添加用户',
    'Create Customer Address' => '添加用户地址',
    'Create Customer Group' => '添加用户组',
    'Created At' => '添加时间',
    'Customer' => '用户',
    'Customer Addresses' => '用户地址',
    'Customer Group' => '用户组',
    'Customer ID' => '用户ID',
    'Default' => '默认',
    'Default Address' => '默认地址',
    'Delete' => '删除',
    'Description' => '描述',
    'District' => '行政区',
    'Email' => '邮箱',
    'Gender' => '性别',
    'ID' => 'ID',
    'Key' => '密匙',
    'Last Login At' => '最后登录时间',
    'Mobile' => '手机',
    'Name' => '名称',
    'Nick Name' => '昵称',
    'Password' => '密码',
    'Password Token' => '密码认证',
    'Point' => '积分',
    'Postcode' => '邮编',
    'Province' => '省份',
    'Reset' => '重置',
    'Search' => '搜索',
    'Sort' => '排序',
    'Stutas' => '状态',
    'Telephone' => '电话',
    'Updated At' => '修改时间',
    'Update' => '修改',
    'Update {modelClass}: ' => '修改 {modelClass}: ',
    'User Name' => '用户名',
    'Password' => '密码',
    'Update Customer' => '修改用户',
    'Customer List' => '用户列表',
    '{username} Addresses' => '{username}的地址',
    '{username} Address' => '{username}的地址',
    'For Customer Name' => '所在账户',
    'View Address' => '查看地址',
    'Add New Address' => '添加新地址',
    'Adress Admin' => '地址管理',
    'Customer Groups' => '用户组',
    'Is Default' => '默认',
    'Top Category' => '顶级分类',
    'Not found a address!' => '没有找到地址！',
];
