<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Frontend call basis for Developer' => '简码作为开发者在前台调用的依据',
	'Example:http://www.turen.pw' => '例如：http://www.turen.pw',
    'Address' => '地址',
    'Contact' => '联系方式',
    'Content' => '主体内容',
    'Customer ID' => '用户',
    'Customer Name' => '用户名',
    'Description' => '描述详情',
    'Education' => '教育背景',
    'Experience' => '工作经验',
    'ID' => 'ID',
    'Ip' => 'IP地址',
    'Is Recommend' => '推荐',
    'Is Top' => '置顶',
    'Lang' => '语言',
    'Link' => '友情链接',
    'Link Type ID' => '链接分类',
    'Link Url' => '链接地址',
    'Mode' => '模式',
    'Name' => '名称',
    'Nickname' => '昵称',
    'Num' => '人数',
    'Parent ID' => '所属分类',
    'Pic Url' => '图片地址',
    'Post Time' => '发布时间',
    'Reply' => '回复',
    'Sex' => '性别',
    'Target' => '跳转方式',
    'Title' => '标题',
    'Workdesc' => '工作描述',
	'Short Code' => '调用简码',
	'Update:' => '更新：',
	'Update' => '更新',
	'Link List' => '友链列表',
	'Create Link' => '添加友链',
	'Job List' => '工作列表',
	'Create Job' => '添加工作',
	'Message List' => '留言列表',
	'Create Message' => '添加留言',
	'Comment List' => '评论列表',
	'Create Comment' => '添加评论',
	'Nav List' => '菜单列表',
	'Create Nav' => '添加菜单',
	'Create Fragment' => '添加碎片',
	'Fragment List' => '碎片列表',
	'Top Nav' => '顶级菜单',
	'Link Type List' => '链接分类列表',
	'Order' => '排序',
	'Re Link Url' => '重写地址',
	'URL Rewrite' => '伪静态地址，用于推广优化，要在系统中配置中开启',
	'Through the title calls this menu' => '这个标题是前台调用的依据，所以如果是菜单的首项时就应当为英文。',
	'Open Type' => '打开方式',
	'Blank' => '新页面打开',
	'Parent' => '你页面打开',
	'Self' => '当前页面打开',
	'Have links under the link type, cannot be deleted.' => '此项目下还有子项目，不能直接删除。',
	'Under this category contains content, cannot be deleted!' => '此分类下包含有内容，不能删除.',
	'Are you sure you want to delete this item?' => '确定要删除此选中项吗？',
	'Create Link Type' => '添加链接类型',
	'Delete' => '删除',
	'Have links under the link type, cannot be deleted' => '此链接类型下有链接存在，不能直接删除',
	'Link Type List' => '链接类型列表',
	'Relative ID' => '相关id',
	'Treatment' => 'sssss',
	'Usefullife' => 'sssss',
];
