<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '你确定要删除选中项吗？',
    'Create Help' => '添加帮助文档',
    'Deleted' => '已删除',
    'Dev Content' => '开发帮助',
    'Don\'t show in the frontend,If you don\'t choose' => '如果勾选，则在前台可以显示',
    'Help List' => '帮助列表',
    'ID' => 'ID',
    'Reset' => '重置',
    'Search' => '搜索',
    'Short Code' => '调用码',
    'Status' => '发布状态',
    'Title' => '标题',
    'Update' => '更新',
    'Update:' => '更新：',
    'Url' => '官方跳转链接',
    'User Content' => '用户帮助',
];
