<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Time' => '添加订单时间',
    'Are you sure you want to delete this item?' => '你确定要删除此选中项吗？',
    'Call List' => '预约列表',
    'Cms Ad ID' => '站内广告',
    'Confirm Time' => '确认订单时间',
    'Consignee' => '用户',
    'Contact' => '联系方式',
    'Country' => '国家',
	'Province' => '省',
	'City' => '市',
	'District' => '地区',
	'Address' => '地址详情',
	'Zipcode' => '邮编',
    'Create Call' => '添加预约',
    'Create Info' => '添加订单',
    'Customer ID' => '注册用户',
    'Deleted' => '删除',
    'Discount' => '优惠金额',
    'Email' => '邮箱',
    'ID' => 'ID',
    'Info List' => '订单列表',
    'Mobile' => '手机',
    'Order Amount' => '订单总额',
    'Order No' => '订单号',
    'Order Note' => '订单备注',
    'Payment Note' => '付款备注',
    'Payment Time' => '付款时间',
    'Referer' => '订单来源',
    'Tel' => '电话',
	'Created At' => '添加时间',
    'Updated At' => '修改时间',
    'Username' => '用户',
];
