<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Code' => '配置块',
    'Key' => '配置标识',
    'Value' => '配置值',
    'Example:' => '例如：',
    'Save Config Success!' => '保存配置成功！',
    'Are you sure you want to delete this item?' => '你确定要删除选中的项吗？',
    'Cascade Datas' => '层级数据',
    'Create' => '添加',
    'Create Cascade Data' => '添加层级数据',
    'Delete' => '删除',
    'Reset' => '重置',
    'Search' => '搜索',
    'Update' => '修改',
    'Update {modelClass}: ' => '修改 {modelClass}：',
    'Data Group' => '数据组',
    'Level' => '级别',
    'Name' => '名称',
    'Parent Id' => '父ID',
    'Area Data' => '区域数据',
    'Certify Data' => '证件类型数据',
    'City' => '市级',
    'Country' => '国家级',
    'Parent' => '父级',
    'Powiat' => '县级',
    'Province' => '省级',
    'Parent Id Is Zero' => '父级为0',
    'Add Chile Data' => '添加子数据',
    'Click View' => '点击查看',
    'View Demo' => '查看DEMO',
    'Create Data For {parent_name}' => '添加数据到“{parent_name}”',
    'Top Category' => '顶级',
    'Access' => '访问控制',
    'General' => '常规选项',
    'Image' => '资源参数',
    'Local' => '本地化选项',
    'Mail' => '邮件配置',
    'Server' => '服务器相关',
    'Site' => '站点配置',
    'Accepts units B KB MB GB if string,default is KB' => '接受的单位为B KB MB GB，默认是KB',
    'Please choose the parent item!' => '请先选择父项！',
    'Is Array' => '是数组',
	'Number of direct interception length of Chinese characters or letters' => '截取的长度为汉字或字母的个数',
];
