<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Request the address wrong' => '请求地址错误',
	'Unknown Error' => '未知错误',
	'Callback parameter is not valid' => 'Callback参数非法',
	'Upload success' => '上传成功',
	'File size over server size configuration' => '文件大小超出了配置器配置（php ini）',
	'File size over form size configuration' => '文件大小超出了表单限制',
	'Local server error' => '服务器局部错误',
	'Not found upload file' => '没有找到上传文件',
	'Not found tmp file' => '没有找到tmp文件',
	'Tmp file cannot be read' => 'Tmp文件不可读',
	'File type was limited by the server' => '文件类型被服务器限制',
	'Not found file' => '文件未找到',
	'File size beyond ueditor limit' => '文件大小超出ueditor限制',
	'Ueditor not allowed file types' => 'ueditor不允许的文件类型',
	'Failed to create the upload directory' => '创建上传目录失败',
	'Do not write to upload directory' => '上传目录不可写',
	'Failed to upload file' => '上传文件失败',
	'Http link error' => 'http链接错误',
	'Http head error' => 'http请求头部错误',
	'Http content type error' => 'http请求内容类型错误',
	'No match file' => '没有匹配的文件',
];









