<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'File Upload' => '文件上传',
    'Image Show' => '图片展示',
    'Cancel' => '取消',
    'Chrome collapse? To solve it' => 'Chrome崩溃问题解决方法',
    'Delete' => '删除',
    'File List' => '文件列表',
    'Limit Numer:<strong>{num}</strong>,File Size:<strong>{fileSize}</strong>,Type:<strong>{fileType}</strong>' => '最大上传个数:<strong>{num}</strong>,单个文件大小:<strong>{fileSize}</strong>,<br />允许文件类型:<strong>{fileType}</strong>',
    'Salt no pass,Invalid Data!' => 'Salt不通过，非法数据',
    'Save' => '保存',
    'Session no pass,Invalid Data!' => 'Session不通过，非法数据',
    'Set Watermark' => '添加水印',
    'The temporary file upload failed, not received upload!' => '临时文件上传失败了,没有收到上传！',
    'Upload timeout,Please refresh Page!' => '上传超时，请重新刷新上传页面！',
    'dir parameter not found' => 'dir参数未找到',
    'num parameter not found' => 'num参数未找到',
    'Add' => '选择文件',
    'Close' => '关闭',
    'Not Found Anything!' => '没有发现任何内容！',
    'frame parameter not found' => 'frame参数未找到',
    'widget parameter not found' => 'widget参数未找到',
    'Delete File Success' => '删除文件成功',
	'Upload picture' => '图片上传',
];
