<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create User' => '添加管理员',
    'Delete failure, group contains the administrator!' => '删除失败，组里面包含管理员！',
    'Users' => '管理员',
    'Email' => '邮箱',
    'Password' => '密码',
    'Real Name' => '真实名',
    'Status' => '状态',
    'User Name' => '用户名',
    'Incorrect username or password.' => '您的用户名或密码错误。',
    'Has already been taken.' => '已经存在此项',
    'Remember Me' => '下次自动登录',
    'Role' => '角色',
    'User Group' => '用户组',
    'Verify Code' => '验证码',
    'Role Name' => '角色名',
    'Log on to your session' => '登录到您的会话',
    'Login' => '登录',
    'Config Admin' => '配置管理',
	'About Us' => '关于我们',
];
